name: flutterred
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  anisi_controls: ^0.0.9
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true